# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Auto-generate and commit

on:
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest nbconvert tensorflow jupyter matplotlib
        pip install -U git+https://bitbucket.org/criterionai/core
    - name: Execute jupyter notebook
      run: |
        git rm generated/. -r
        python -m jupyter nbconvert --to markdown --execute --ExecutePreprocessor.kernel_name=python ./code/developers/python-sdk-brevettiai/data-science-tools/brevetti_image_tools.ipynb  --output-dir ./generated/developers/python-sdk-brevettiai/data-science-tools/
        git add generated/.
        git commit -m "Push by workflow_dispatch action"
        git push
    - name: Archive markdown file
      uses: actions/upload-artifact@v2
      with:
        name: markdown-with-images
        path: |
          generated
